image: node

stages:
  - build
  - test
  - deploy review
  - deploy staging
  - deploy production
  - production test
  - cache


cache: 
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull


variables:
  STAGING_DOMAIN: ARR191Professional-staging.surge.sh
  PRODUCTION_DOMAIN: ARR191Professional.surge.sh


update cache:
  stage: cache
  script:
    - npm install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: push
  only:
    - schedules


build website:
  stage: build
  cache: {}
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
    - echo "This job runs in merge request pipelines"
  artifacts:
    paths:
      - ./public
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH != "schedule"


test artifacts:
  image: alpine
  stage: test
  cache: {}
  script:
    - grep -q "Gatsby" ./public/index.html
    - echo "This job runs in merge request pipelines"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH != "schedule"


test website:
  stage: test
  cache:
    policy: pull
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"
    - echo "This job runs in merge request pipelines"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH != "schedule"


deploy review:
  stage: deploy review
  only:
    - merge_requests
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://ARR191Professional-$CI_ENVIRONMENT_SLUG.surge.sh
  script:
  - npm install --global surge
  - surge --project ./public --domain ARR191Professional-$CI_ENVIRONMENT_SLUG.surge.sh

.deploy_template: &deploy
  only:
    - main
  script:
    - npm install --global surge
    - surge --project ./public --domain $DOMAIN
  environment: 
    name: $STAGE
    url: https://$DOMAIN
  cache:
    policy: pull
  except:
    - schedules

deploy staging:
  <<: *deploy
  stage: deploy staging
  variables: 
    DOMAIN: $STAGING_DOMAIN
    STAGE: staging


deploy production:
  <<: *deploy
  stage: deploy production
  variables: 
    DOMAIN: $PRODUCTION_DOMAIN
    STAGE: production  
  when: manual
  allow_failure: false


test deployed website:
  stage: production test
  image: alpine
  only:
    - main
  cache: {}
  script:
    - apk add --no-cache curl
    - curl -s "https://arr191professional.surge.sh/" | grep -q "Gatsby"
    - curl -s "https://arr191professional.surge.sh/" | grep -q "$CI_COMMIT_SHORT_SHA"
  except:
    - schedules