image: node

stages:
  - build
  - test
  - deploy
  - deployment test

build website:
  stage: build
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./public


test artifacts:
  image: alpine
  stage: test
  script:
    - grep -q "Gatsby" ./public/index.html

test website:
  stage: test
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"

deploy website to surge:
  stage: deploy
  script:
    - npm install --global surge
    - surge --project ./public --domain ARR191Professional.surge.sh

test deployed website:
  stage: deployment test
  image: alpine
  script:
    - apk add curl
    - curl "https://arr191professional.surge.sh/" | tac | tac | grep -q "Gatsby"