image: node

stages:
  - build
  - test
  - deploy review
  - deploy staging
  - deploy production
  - production test
  - cache

cache: 
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull

variables:
  STAGING_DOMAIN: ARR191Professional-staging.surge.sh
  PRODUCTION_DOMAIN: ARR191Professional.surge.sh

update cache:
  stage: cache
  script:
    - npm install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: push
  only:
    - schedules

build website:
  stage: build
  cache: {}
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
    - echo "This job runs in merge request pipelines"
  artifacts:
    paths:
      - ./public
  except:
    - schedules
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

test artifacts:
  image: alpine
  stage: test
  cache: {}
  script:
    - grep -q "Gatsby" ./public/index.html
    - echo "This job runs in merge request pipelines"
  except:
    - schedules
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'


test website:
  stage: test
  cache:
    policy: pull
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"
    - echo "This job runs in merge request pipelines"
  except:
    - schedules
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'


deploy review:
  stage: deploy review
  only:
    - merge_requests
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://ARR191Professional-$CI_ENVIRONMENT_SLUG.surge.sh
  script:
  - npm install --global surge
  - surge --project ./public --domain ARR191Professional-$CI_ENVIRONMENT_SLUG.surge.sh

deploy staging:
  stage: deploy staging
  environment: 
    name: staging
    url: https://$STAGING_DOMAIN
  only:
    - main
  cache:
    policy: pull
  script:
    - npm install --global surge
    - surge --project ./public --domain $STAGING_DOMAIN
  except:
    - schedules

deploy production:
  stage: deploy production
  environment: 
    name: production
    url: https://$PRODUCTION_DOMAIN
  only:
    - main
  when: manual
  allow_failure: false
  cache:
    policy: pull
  script:
    - npm install --global surge
    - surge --project ./public --domain $PRODUCTION_DOMAIN
  except:
    - schedules

test deployed website:
  stage: production test
  image: alpine
  only:
    - main
  cache: {}
  script:
    - apk add --no-cache curl
    - curl -s "https://arr191professional.surge.sh/" | grep -q "Gatsby"
    - curl -s "https://arr191professional.surge.sh/" | grep -q "$CI_COMMIT_SHORT_SHA"
  except:
    - schedules